# Time-based features

In [ ]:
import pandas as pd

df=pd.read_csv("../inputs/training.csv")
df=df.sort_values(by=['tcp_stream','protocol','start_time'])
df[['flow_start']]=df[['flow_start']].apply(pd.to_datetime)
df[['flow_finish']]=df[['flow_finish']].apply(pd.to_datetime)
pd.set_option("display.precision", 50)
df.columns

In [ ]:
df['total_packets']

In [64]:
import pickle

df_normal=pickle.load( open( "../src/df_flows_normal.pickle", "rb" ) )
len(df_normal)

151904

In [67]:
df_attack=pickle.load( open( "../src/df_flows_attack.pickle", "rb" ) )
len(df_attack)
df_attack=df_attack.head()

,src_ip,dst_ip,src_port,dst_port,fwd_packets,bwd_packets,fwd_bytes,bwd_bytes,fwd_duration,flow_start,...,bwd_max_bytes,flow_duration,count_dest,count_src,count_serv_src,count_serv_dst,count_dest_conn,count_src_conn,count_serv_src_conn,count_count_serv_src_conn
0,192.168.10.17,172.217.10.34,43060,443,10,9,0,0,75.239665,2017-07-07 17:00:00.014,...,0.0,75.239,0,0,0,0,0,0,0,0
1,192.168.10.17,172.217.10.34,43060,443,1,0,31,0,0.000000,2017-07-07 17:01:15.216,...,NaN,NaN,13,1,15,0,38,1,76,0
2,172.217.10.46,192.168.10.17,80,55848,12,12,0,0,105.228651,2017-07-07 17:00:00.026,...,0.0,105.229,0,0,0,0,0,0,0,0
3,192.168.10.51,162.213.33.50,59225,443,2,3,0,0,0.108321,2017-07-07 17:00:00.063,...,0.0,0.205,0,0,0,0,0,0,0,0
4,162.213.33.50,192.168.10.51,443,59225,2,1,549,197,0.108172,2017-07-07 17:00:00.063,...,197.0,0.010,0,0,0,0,0,0,0,0

In [9]:
test2=test.sort_values(by=['bwd_packets'])

In [42]:
t1=test2[-4:2]
t2=test2[2:4]
t3=test2[4:6]

In [48]:
test2

,src_ip,dst_ip,src_port,dst_port,fwd_packets,bwd_packets,fwd_bytes,bwd_bytes,fwd_duration,flow_start,...,bwd_max_bytes,flow_duration,count_dest,count_src,count_serv_src,count_serv_dst,count_dest_conn,count_src_conn,count_serv_src_conn,count_serv_dst_conn
7,192.168.10.17,122.225.115.206,33540,443,1,0,180,0,0.000000,2017-07-07 17:06:09.126,...,NaN,NaN,1,1,1,0,3,1,4,0
10,192.168.10.12,151.101.130.49,50922,443,1,0,200,0,0.000000,2017-07-07 17:49:17.228,...,NaN,NaN,2,1,2,0,2,1,2,0
13,192.168.10.12,52.84.145.211,54604,443,1,0,199,0,0.000000,2017-07-07 17:49:17.228,...,NaN,NaN,2,1,2,0,2,1,2,0
5,104.27.145.38,192.168.10.17,80,45648,2,1,0,0,0.015397,2017-07-07 17:00:03.193,...,0.0,0.000,0,1,0,0,0,1,0,0
8,122.225.115.206,192.168.10.17,443,33540,7,2,13414,523,1.612500,2017-07-07 17:06:09.537,...,373.0,0.406,0,0,0,2,0,3,0,5
14,52.84.145.211,192.168.10.12,443,54604,11,3,10319,1031,0.657490,2017-07-07 17:49:17.254,...,529.0,0.595,0,1,0,4,0,1,0,4
9,192.168.10.12,151.101.130.49,50922,443,23,7,0,2896,86.585583,2017-07-07 17:49:17.100,...,1448.0,86.586,0,0,0,0,0,0,0,0
11,151.101.130.49,192.168.10.12,443,50922,17,13,11320,6033,86.439117,2017-07-07 17:49:17.247,...,1171.0,61.840,0,0,0,4,0,0,0,4
6,192.168.10.17,122.225.115.206,33540,443,34,35,0,57410,2.823479,2017-07-07 17:06:08.724,...,4380.0,3.223,0,0,0,0,2,0,3,0
12,192.168.10.12,52.84.145.211,54604,443,51,43,0,49232,86.592590,2017-07-07 17:49:17.100,...,2896.0,86.593,0,0,0,0,0,0,0,0

In [53]:
i=6
c=i-5
t1=test2[max(0,c):i]
t1

,src_ip,dst_ip,src_port,dst_port,fwd_packets,bwd_packets,fwd_bytes,bwd_bytes,fwd_duration,flow_start,...,bwd_max_bytes,flow_duration,count_dest,count_src,count_serv_src,count_serv_dst,count_dest_conn,count_src_conn,count_serv_src_conn,count_serv_dst_conn
10,192.168.10.12,151.101.130.49,50922,443,1,0,200,0,0.000000,2017-07-07 17:49:17.228,...,NaN,NaN,2,1,2,0,2,1,2,0
13,192.168.10.12,52.84.145.211,54604,443,1,0,199,0,0.000000,2017-07-07 17:49:17.228,...,NaN,NaN,2,1,2,0,2,1,2,0
5,104.27.145.38,192.168.10.17,80,45648,2,1,0,0,0.015397,2017-07-07 17:00:03.193,...,0.0,0.000,0,1,0,0,0,1,0,0
8,122.225.115.206,192.168.10.17,443,33540,7,2,13414,523,1.612500,2017-07-07 17:06:09.537,...,373.0,0.406,0,0,0,2,0,3,0,5
14,52.84.145.211,192.168.10.12,443,54604,11,3,10319,1031,0.657490,2017-07-07 17:49:17.254,...,529.0,0.595,0,1,0,4,0,1,0,4

In [59]:
ef=pickle.load( open( "../src/fe3/attack_test.pickle", "rb" ) )
ef[['protocol','src_ip','dst_ip','fwd_packets','bwd_packets','bwd_avg_bytes']]

,protocol,src_ip,dst_ip,fwd_packets,bwd_packets,bwd_avg_bytes
0,TCP,192.168.10.17,172.217.10.34,10,9,0.000000
1,TLSv1.2,192.168.10.17,172.217.10.34,1,0,NaN
2,TCP,172.217.10.46,192.168.10.17,12,12,0.000000
3,TCP,192.168.10.17,23.45.196.15,9,9,0.000000
4,TLSv1.2,23.45.196.15,192.168.10.17,1,0,NaN
5,TCP,104.27.145.38,192.168.10.17,2,1,0.000000
6,TCP,104.97.137.26,192.168.10.50,3,1,0.000000
7,TCP,192.168.10.17,122.225.115.206,34,35,1640.285714
8,TLSv1,192.168.10.17,122.225.115.206,1,0,NaN
9,TLSv1.2,122.225.115.206,192.168.10.17,7,2,261.500000
10,TCP,192.168.10.17,122.225.115.206,8,4,0.000000
11,TLSv1,192.168.10.17,122.225.115.206,1,0,NaN
12,TLSv1.2,122.225.115.206,192.168.10.17,3,2,64.000000
13,TCP,192.168.10.17,122.225.115.206,25,36,1624.750000
14,TLSv1,192.168.10.17,122.225.115.206,1,0,NaN
15,TLSv1.2,122.225.115.206,192.168.10.17,7,2,261.500000
16,TCP,192.168.10.17,122.225.115.206,10,8,961.125000
17,TLSv1,192.168.10.17,122.225.115.206,1,0,NaN
18,TLSv1.2,122.225.115.206,192.168.10.17,4,2,261.500000
19,TCP,192.168.10.17,122.225.115.206,9,9,1135.555556
20,TLSv1,192.168.10.17,122.225.115.206,1,0,NaN
21,TLSv1.2,122.225.115.206,192.168.10.17,4,2,261.500000
22,TCP,192.168.10.17,122.225.34.188,11,5,0.200000
23,TLSv1,192.168.10.17,122.225.34.188,1,0,NaN
24,TLSv1.2,122.225.34.188,192.168.10.17,5,2,96.500000
25,SSLv3,192.168.10.51,162.213.33.50,1,0,NaN
26,TCP,192.168.10.51,162.213.33.50,7,7,0.000000
27,TLSv1.2,162.213.33.50,192.168.10.51,4,3,185.000000
28,TCP,192.168.10.17,183.232.151.251,32,17,0.058824
29,TLSv1,192.168.10.17,183.232.151.251,1,0,NaN
...,...,...,...,...,...,...
2553,TCP,107.22.224.100,192.168.10.50,1,1,0.000000
2554,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2555,TCP,146.20.128.189,192.168.10.50,1,1,0.000000
2556,TCP,13.59.43.55,192.168.10.50,1,1,0.000000
2557,TCP,146.20.128.189,192.168.10.50,3,1,0.000000
2558,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2559,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2560,TCP,146.20.128.223,192.168.10.50,1,1,0.000000
2561,TCP,107.22.224.100,192.168.10.50,1,1,0.000000
2562,TCP,107.22.224.100,192.168.10.50,1,1,0.000000
2563,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2564,TCP,146.20.128.223,192.168.10.50,1,1,0.000000
2565,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2566,TCP,192.168.10.50,151.101.192.194,1,1,0.000000
2567,TCP,104.97.137.26,192.168.10.50,1,1,0.000000
2568,TCP,146.20.128.189,192.168.10.50,1,1,0.000000
2569,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2570,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2571,TCP,146.20.128.189,192.168.10.50,1,1,0.000000
2572,TCP,104.97.137.26,192.168.10.50,1,1,0.000000
2573,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2574,TCP,107.22.224.100,192.168.10.50,1,1,0.000000
2575,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2576,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2577,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2578,TCP,151.101.192.194,192.168.10.50,1,1,0.000000
2579,TCP,151.101.192.194,192.168.10.50,1,1,0.000000
2580,TCP,146.20.128.223,192.168.10.50,1,1,0.000000
2581,TCP,13.58.146.190,192.168.10.50,1,1,0.000000
2582,TCP,13.58.146.190,192.168.10.50,1,1,0.000000